baseURL = 'https://babsopvoorne.nl/'
languageCode = 'nl-nl'
title = 'Babs op Voorne'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/#home"
    weight = 10
  [[menu.main]]
    name = "Over mij"
    url = "/#over-mij"
    weight = 20
  [[menu.main]]
    name = "Werkwijze"
    url = "/#werkwijze"
    weight = 30
  [[menu.main]]
    name = "Blog"
    url = "/#blog"
    weight = 40
  [[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 50
