# netlify.toml

[build]
  # De command die Netlify moet uitvoeren om je site te bouwen
  command = "hugo --minify"
  # De map waar de gebouwde site zich bevindt
  publish = "public"

[build.environment]
  # Specificeer de Hugo-versie die Netlify moet gebruiken.
  # Gebruik hier een recente, stabiele versie.
  # Je kunt de nieuwste versies vinden op: https://github.com/gohugoio/hugo/releases
  HUGO_VERSION = "0.148.1" # Geüpdatet naar de nieuwste stabiele versie

# Optionele configuratie voor de Decap CMS admin
[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

# Configuratie voor Netlify Forms
# Zorg ervoor dat je formulier in je HTML een data-netlify="true" attribuut heeft.
# Bijvoorbeeld: <form name="contact" method="POST" data-netlify="true">
[forms]
  # Je kunt hier extra configuratie toevoegen voor je formulieren,
  # zoals spamfiltering of meldingen. Voor nu laten we het leeg.
  # Netlify detecteert formulieren automatisch op basis van het data-netlify attribuut.
