# config.yml voor Decap CMS
# Dit bestand definieert de structuur van je content en hoe deze in de Git repository wordt opgeslagen.

backend:
  # Voor GitHub Pages of Netlify, gebruik Git Gateway via Netlify Identity
  name: git-gateway
  branch: main # De branch waar je content op staat (meestal 'main' of 'master')

publish_mode: editorial_workflow # Optioneel: Schakel een publicatieworkflow in (concept, in review, gepubliceerd)
media_folder: "static/uploads" # De map waar geüploade afbeeldingen worden opgeslagen (relatief aan de root van je Hugo project)
public_folder: "/uploads" # De publieke URL voor de afbeeldingen (relatief aan de root van je website)

# Collecties: Definieer hier je content types
collections:
  - name: "pages" # Interne naam voor de collectie
    label: "Pagina's" # Weergavenaam in het CMS
    files: # Gebruik 'files' voor singleton pagina's (pagina's die maar één keer voorkomen)
      - file: "content/_index.md" # Pad naar het Markdown bestand voor de homepagina
        label: "Homepagina"
        name: "home"
        fields:
          - {label: "Titel", name: "title", widget: "string", default: "Home"}
          - {label: "SEO Titel", name: "seo_title", widget: "string", required: false, hint: "Titel voor zoekmachines (max. 60 tekens)"}
          - {label: "SEO Beschrijving", name: "seo_description", widget: "text", required: false, hint: "Korte beschrijving voor zoekmachines (max. 160 tekens)"}
          - {label: "Headline", name: "headline", widget: "string", hint: "Pakkende hoofdzin op de homepagina"}
          - {label: "Subheadline", name: "subheadline", widget: "string", hint: "Ondersteunende zin onder de headline"}
          - {label: "Hero Afbeelding", name: "hero_image", widget: "image", required: false, hint: "Grote sfeervolle afbeelding bovenaan de homepagina"}
          - {label: "Introductie Tekst", name: "intro_text", widget: "markdown", hint: "Korte introductie over de BABS en aanpak"}
          - {label: "CTA 1 Tekst", name: "cta1_text", widget: "string", default: "Onze Werkwijze Ontdekken"}
          - {label: "CTA 1 Link", name: "cta1_link", widget: "string", default: "/werkwijze/"}
          - {label: "CTA 2 Tekst", name: "cta2_text", widget: "string", default: "Neem Contact Op"}
          - {label: "CTA 2 Link", name: "cta2_link", widget: "string", default: "/contact/"}
          - {label: "Geografische Focus Tekst", name: "geo_focus_text", widget: "string", default: "Jouw BABS in Voorne-Putten en Omgeving: Hellevoetsluis, Brielle, Westvoorne, Nissewaard en meer."}

      - file: "content/over-mij.md" # Pad naar het Markdown bestand voor de Over mij pagina
        label: "Over mij"
        name: "about"
        fields:
          - {label: "Titel", name: "title", widget: "string", default: "Over mij"}
          - {label: "SEO Titel", name: "seo_title", widget: "string", required: false}
          - {label: "SEO Beschrijving", name: "seo_description", widget: "text", required: false}
          - {label: "Inhoud", name: "body", widget: "markdown", hint: "Persoonlijke introductie van de BABS"}
          - {label: "Portretfoto", name: "portrait_image", widget: "image", required: false, hint: "Professionele portretfoto van de BABS"}
          - {label: "Kernwaarden", name: "values", widget: "list", field: {label: "Waarde", name: "value", widget: "string"}, hint: "Lijst van kernwaarden (bijv. respect, eerlijkheid)"}

      - file: "content/werkwijze.md" # Pad naar het Markdown bestand voor de Werkwijze pagina
        label: "Werkwijze"
        name: "process"
        fields:
          - {label: "Titel", name: "title", widget: "string", default: "Werkwijze"}
          - {label: "SEO Titel", name: "seo_title", widget: "string", required: false}
          - {label: "SEO Beschrijving", name: "seo_description", widget: "text", required: false}
          - {label: "Introductie Tekst", name: "intro_text", widget: "markdown", required: false, hint: "Korte introductie van de werkwijze"}
          - {label: "Stappen", name: "steps", widget: "list", hint: "Definieer de stappen van de werkwijze", fields: [{label: "Titel", name: "title", widget: "string"}, {label: "Beschrijving", name: "description", widget: "markdown"}]}
          - {label: "FAQ Introductie", name: "faq_intro", widget: "markdown", required: false, hint: "Introductietekst voor de FAQ sectie"}
          - {label: "FAQ Items", name: "faq_items", widget: "list", hint: "Veelgestelde vragen en antwoorden", fields: [{label: "Vraag", name: "question", widget: "string"}, {label: "Antwoord", name: "answer", widget: "markdown"}]}

      - file: "content/contact.md" # Pad naar het Markdown bestand voor de Contact pagina
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Titel", name: "title", widget: "string", default: "Contact"}
          - {label: "SEO Titel", name: "seo_title", widget: "string", required: false}
          - {label: "SEO Beschrijving", name: "seo_description", widget: "text", required: false}
          - {label: "Introductie Tekst", name: "intro_text", widget: "markdown", hint: "Korte introductie voor het contactformulier"}
          - {label: "Reactietijd Tekst", name: "response_time_text", widget: "string", default: "Ik streef ernaar om binnen 24 uur te reageren."}
          - {label: "E-mailadres", name: "email", widget: "string", required: false, hint: "Direct e-mailadres"}
          - {label: "Telefoonnummer", name: "phone", widget: "string", required: false, hint: "Direct telefoonnummer"}
          - {label: "Privacyverklaring Tekst", name: "privacy_text", widget: "markdown", hint: "Beknopte privacyverklaring voor het contactformulier"}

  - name: "blog" # Collectie voor blogposts
    label: "Blogposts"
    folder: "content/blog" # Map waar blogposts worden opgeslagen
    create: true # Sta het aanmaken van nieuwe items toe
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Bestandsnaam formaat (bijv. 2025-07-10-mijn-blogpost.md)
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "SEO Titel", name: "seo_title", widget: "string", required: false}
      - {label: "SEO Beschrijving", name: "seo_description", widget: "text", required: false}
      - {label: "Publicatiedatum", name: "date", widget: "datetime"}
      - {label: "Auteur", name: "author", widget: "string", default: "Babs op Voorne"}
      - {label: "Featured Afbeelding", name: "featured_image", widget: "image", required: false, hint: "Afbeelding die bovenaan de blogpost wordt weergegeven"}
      - {label: "Introductie", name: "intro", widget: "text", hint: "Korte introductietekst voor de blogpost"}
      - {label: "Inhoud", name: "body", widget: "markdown", hint: "De volledige inhoud van de blogpost (Markdown)"}
      - {label: "Tags", name: "tags", widget: "list", required: false, default: [], hint: "Tags voor de blogpost (bijv. 'tips', 'locaties')"}
      - {label: "Categorieën", name: "categories", widget: "list", required: false, default: [], hint: "Categorieën voor de blogpost (bijv. 'trouwen', 'inspiratie')"}

  - name: "testimonials" # Collectie voor testimonials
    label: "Testimonials"
    folder: "content/testimonials" # Map waar testimonials worden opgeslagen
    create: true
    slug: "{{slug}}" # Bestandsnaam formaat (bijv. sarah-mark.md)
    fields:
      - {label: "Naam Bruidspaar", name: "couple_name", widget: "string"}
      - {label: "Quote", name: "quote", widget: "text"}
      - {label: "Trouwdatum (optioneel)", name: "wedding_date", widget: "datetime", required: false}
